export const SUPPORTED_LANGUAGES = [
    { id: "c", name: "C", version: "5.3.0", extension: ".c", monacoId: "c" },
    { id: "cpp", name: "C++", version: "5.3.0", extension: ".cpp", monacoId: "cpp" },
    { id: "java", name: "Java", version: "15.0.2", extension: ".java", monacoId: "java" },
    { id: "python", name: "Python", version: "3.10.0", extension: ".py", monacoId: "python" },
    { id: "javascript", name: "JavaScript", version: "18.15.0", extension: ".js", monacoId: "javascript" },
    { id: "typescript", name: "TypeScript", version: "5.0.3", extension: ".ts", monacoId: "typescript" },
    { id: "go", name: "Go", version: "1.16.2", extension: ".go", monacoId: "go" },
    { id: "rust", name: "Rust", version: "1.68.2", extension: ".rs", monacoId: "rust" },
    { id: "kotlin", name: "Kotlin", version: "1.8.20", extension: ".kt", monacoId: "kotlin" },
    { id: "swift", name: "Swift", version: "5.3.3", extension: ".swift", monacoId: "swift" },
    { id: "csharp", name: "C#", version: "6.12.0", extension: ".cs", monacoId: "csharp" },
    { id: "php", name: "PHP", version: "8.2.3", extension: ".php", monacoId: "php" },
    { id: "ruby", name: "Ruby", version: "3.0.1", extension: ".rb", monacoId: "ruby" },
    { id: "r", name: "R", version: "4.1.0", extension: ".r", monacoId: "r" },
    { id: "scala", name: "Scala", version: "3.2.1", extension: ".scala", monacoId: "scala" },
    { id: "perl", name: "Perl", version: "5.34.0", extension: ".pl", monacoId: "perl" },
    { id: "lua", name: "Lua", version: "5.3.5", extension: ".lua", monacoId: "lua" },
    { id: "dart", name: "Dart", version: "2.19.6", extension: ".dart", monacoId: "dart" },
    { id: "sql", name: "SQL", version: "3.36.0", extension: ".sql", monacoId: "sql" },
    { id: "bash", name: "Bash", version: "5.2.0", extension: ".sh", monacoId: "shell" },
];
