import { create } from "zustand";
export const useTestStore = create((set) => ({
    currentTest: null,
    currentQuestion: null,
    currentAttempt: null,
    code: "",
    language: "javascript",
    output: "",
    isRunning: false,
    isSubmitting: false,
    violations: [],
    submissions: [],
    timeRemaining: 0,
    fullscreen: false,
    setCurrentTest: (test) => set({ currentTest: test }),
    setCurrentQuestion: (question) => set({ currentQuestion: question, code: question?.starterCode?.["javascript"] || "" }),
    setCode: (code) => set({ code }),
    setLanguage: (language) => set({ language }),
    setOutput: (output) => set({ output }),
    setIsRunning: (running) => set({ isRunning: running }),
    setIsSubmitting: (submitting) => set({ isSubmitting: submitting }),
    addViolation: (violation) => set((state) => ({ violations: [...state.violations, violation] })),
    addSubmission: (submission) => set((state) => ({ submissions: [...state.submissions, submission] })),
    setTimeRemaining: (time) => set({ timeRemaining: time }),
    setFullscreen: (fullscreen) => set({ fullscreen }),
    setCurrentAttempt: (attempt) => set({ currentAttempt: attempt }),
    tick: () => set((state) => ({ timeRemaining: Math.max(0, state.timeRemaining - 1) })),
}));
